config/routes.rb
require 'api_constraints'

ClickerAutomationApi::Application.routes.draw do

  devise_for :dusers

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :crawler_configs do
        resources :crawl_histories do
          get :manage, :on => :collection
        end
      end
      
      resources :crawler_configs
      resources :crawl_histories
    end
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :dusers
  end
  
  resources :crawler_configs do
    resources :crawl_histories
  end

  root :to => 'crawler_configs#index'

end

app/models/duser.rb
class Duser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
  
  def to_s
  "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/dusers_controller.rb
class Admin::DusersController < Admin::BaseController
  
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  
  def index
      @dusers = Duser.all(:order => "email")
  end
  
  def show
  end

  def edit
  end
  
  def update
    if params[:duser][:password].blank?
      params[:duser].delete(:password)
      params[:duser].delete(:password_confirmation)
    end
    set_admin
    if @duser.update_attributes(params[:duser])
      flash[:notice] = "User has been updated."
      redirect_to admin_dusers_path
    else
      flash[:alert] = "User has not been updated."
      render :action => "edit"
    end
  end
  
  def new
      @duser = Duser.new
  end
  
  def destroy
    if @duser == current_duser
      flash[:alert] = "You cannot delete yourself!"
    else
      @duser.destroy
      flash[:notice] = "User has been deleted."
    end

    redirect_to admin_dusers_path
  end
  
  def create
    @duser = Duser.new(params[:duser])
    set_admin
    if @duser.save
      flash[:notice] = "User has been created."
      redirect_to admin_dusers_path
    else
      flash[:alert] = "User has not been created."
      render :action => "new"
    end
  end
  
  private
    def find_user
      @duser = Duser.find(params[:id])
    end
  
    def set_admin
      @duser.admin = params[:duser][:admin] == "1"
    end
end

app/helpers/admin/dusers_helper.rb
module Admin::DusersHelper
end

app/views/admin/dusers/_form.html.erb
<%= form_for [:admin, @duser] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.check_box :admin %>
    <%= f.label :admin, "Is an admin?" %>
  </p>
  <%= f.submit %>
<% end %>

app/views/admin/dusers/edit.html.erb
<%= render "form" %>

app/views/admin/dusers/index.html.erb
<%= link_to "New User", new_admin_duser_path %>
<ul>
  <% @dusers.each do |duser| %>
    <li><%= link_to duser, [:admin, duser] %></li>
  <% end %>
</ul>

app/views/admin/dusers/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/dusers/show.html.erb
<h2><%= @duser %></h2>
<%= link_to "Edit User", edit_admin_duser_path(@duser) %>
<%= link_to "Delete User", admin_duser_path(@duser), :method => :delete, 
            :confirm => "Are you sure you want to delete this user?" %>