config/routes.rb
require 'api_constraints'

ClickerAutomationApi::Application.routes.draw do

  devise_for :dusers

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :crawler_configs do
        resources :crawl_histories do
          get :manage, :on => :collection
        end
      end
      
      resources :crawler_configs
      resources :crawl_histories
    end
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :dusers
  end
  
  resources :crawler_configs do
    resources :crawl_histories
  end

  root :to => 'crawler_configs#index'

end

app/models/crawler_config.rb
class CrawlerConfig < ActiveRecord::Base
  self.primary_key="crawlerConfigId"
  self.table_name = "crawler_config"
  attr_accessible :description, :crawlingEnabled, :intervalInHours, :allowedFilters, :useSourceId, :startURL, :distributorProfileId, :mediaTypeId, :maxDepth
  
  validates :startURL, :presence => true
  
  has_many :crawl_histories, :foreign_key => "crawlerConfigId", :dependent => :delete_all
  has_many :permissions, :as => :thing
  
  scope :readable_by, lambda { |duser|
    joins(:permissions).where(:permissions => { :action => "view",
                                                :duser_id => duser.id })
  }
  
  def self.for(duser)
    duser.admin? ? CrawlerConfig : CrawlerConfig.readable_by(duser)
  end
  
end

app/controllers/api/v1/crawler_configs_controller.rb
module Api
  module V1
    class CrawlerConfigsController < ApplicationController

      respond_to :json, :xml

      # GET /crawler_configs
      # GET /crawler_configs.json
      def index
        @crawler_configs = CrawlerConfig.all
      end

      # GET /crawler_configs/1
      # GET /crawler_configs/1.json
      def show
        @crawler_config = CrawlerConfig.find(params[:id])
      end

      # GET /crawler_configs/new
      # GET /crawler_configs/new.json
      def new
        @crawler_config = CrawlerConfig.new
      end

      # GET /crawler_configs/1/edit
      def edit
        @crawler_config = CrawlerConfig.find(params[:id])
      end

      # POST /crawler_configs
      # POST /crawler_configs.json
      def create
        @crawler_config = CrawlerConfig.new(params[:crawler_config])
        @crawler_config.save
        respond_with @crawler_config
      end

      # PUT /crawler_configs/1
      # PUT /crawler_configs/1.json
      def update
        @crawler_config = CrawlerConfig.find(params[:id])
        @crawler_config.update_attributes(params[:crawler_config])
        respond_with @crawler_config
      end

      # DELETE /crawler_configs/1
      # DELETE /crawler_configs/1.json
      def destroy
        @crawler_config = CrawlerConfig.find(params[:id])
        @crawler_config.destroy
        respond_with @crawler_config
      end
    end
  end
end

app/controllers/crawler_configs_controller.rb
class CrawlerConfigsController < ApplicationController
  
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_duser!, :only => [:index, :show]
  before_filter :find_crawler_config, :only => [:show, :edit, :update, :destroy]
  
  respond_to :json, :xml
  
  # GET /crawler_configs
  # GET /crawler_configs.json
  def index
    @crawler_configs = CrawlerConfig.for(current_duser).all
  end

  # GET /crawler_configs/1
  # GET /crawler_configs/1.json
  def show
  end

  # GET /crawler_configs/new
  # GET /crawler_configs/new.json
  def new
    @crawler_config = CrawlerConfig.new
  end

  # GET /crawler_configs/1/edit
  def edit
  end

  # POST /crawler_configs
  # POST /crawler_configs.json
  def create
    @crawler_config = CrawlerConfig.new(params[:crawler_config])
    if @crawler_config.save
      flash[:notice] = "Crawler Config has been created!"
      redirect_to @crawler_config
    else
      flash[:alert] = "Crawler Config has NOT been created!"
      render :action => "new"
    end
  end

  # PUT /crawler_configs/1
  # PUT /crawler_configs/1.json
  def update
    if @crawler_config.update_attributes(params[:crawler_config])
      flash[:notice] = "Crawler Config has been updated!"
      redirect_to @crawler_config
    else
      flash[:alert] = "Crawler Config has NOT been updated!"
      render :action => "edit"
    end
  end

  # DELETE /crawler_configs/1
  # DELETE /crawler_configs/1.json
  def destroy
    @crawler_config.destroy
    flash[:notice] = "Crawler Config has been deleted!"
    redirect_to crawler_configs_path
  end
  
  private
    def find_crawler_config
      #@crawler_config = CrawlerConfig.find(params[:id])
      @crawler_config = CrawlerConfig.for(current_duser).find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The crawler config you were looking" +
                      " for could not be found."
      redirect_to crawler_configs_path
    end
end

app/helpers/crawler_configs_helper.rb
module CrawlerConfigsHelper
end

app/views/crawler_configs/_form.html.erb
<%= form_for(@crawler_config) do |f| %>
  <% if @crawler_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crawler_config.errors.count, "error") %> prohibited this crawler_config from being saved:</h2>

      <ul>
      <% @crawler_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :crawlingEnabled %><br />
    <%= f.text_field :crawlingEnabled %>
  </div>
  <div class="field">
    <%= f.label :startURL %><br />
    <%= f.text_field :startURL %>
  </div>
  <div class="field">
    <%= f.label :mediaTypeId %><br />
    <%= f.text_field :mediaTypeId %>
  </div>
  <div class="field">
    <%= f.label :distributorProfileId %><br />
    <%= f.text_field :distributorProfileId %>
  </div>
  <div class="field">
    <%= f.label :maxDepth %><br />
    <%= f.text_field :maxDepth %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crawler_configs/edit.html.erb
<h1>Editing crawler_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @crawler_config %> |
<%= link_to 'Back', crawler_configs_path %>

app/views/crawler_configs/index.html.erb
<h1>Listing crawler_configs</h1>

<table>
  <tr>
	<th/>
	<th/>
	<th/>
    <th>crawlerConfigId</th>
    <th>description</th>
    <th>crawlingEnabled</th>
    <th>startURL</th>
    <th></th>
  </tr>

<% @crawler_configs.each do |crawler_config| %>
  <tr>	
    <td><%= link_to 'Show', crawler_config %></td>
    <td><%= link_to 'Edit', edit_crawler_config_path(crawler_config) %></td>
    <td><%= link_to 'Destroy', crawler_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= crawler_config.crawlerConfigId %></td>
    <td><%= crawler_config.description %></td>
    <td><%= crawler_config.crawlingEnabled %></td>
    <td><%= crawler_config.startURL %></td>
  </tr>
<% end %>
</table>

<br />

<%= admins_only do %>
<%= link_to 'New Crawler Config', new_crawler_config_path %>
<% end %>

app/views/crawler_configs/new.html.erb
<h1>New crawler_config</h1>

<%= render 'form' %>

<%= link_to 'Back', crawler_configs_path %>

app/views/crawler_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @crawler_config.description %>
</p>

<p>
  <b>crawlingEnabled:</b>
  <%= @crawler_config.crawlingEnabled %>
</p>

<p>
  <b>startURL:</b>
  <%= @crawler_config.startURL %>
</p>

<p>
  <b>intervalInHours:</b>
  <%= @crawler_config.intervalInHours %>
</p>

<p>
  <b>useSourceId:</b>
  <%= @crawler_config.useSourceId %>
</p>

<% admins_only do %>
<%= link_to 'Edit', edit_crawler_config_path(@crawler_config) %> |
<%= link_to "Delete Crawler Config", @crawler_config, :method => :delete, :confirm => "Are you sure you want to delete this crawler config?" %> |
<% end %>
<%= link_to 'Back', crawler_configs_path %>

<br>

<%= link_to "New Crawl History", new_crawler_config_crawl_history_path(@crawler_config) %>

<h3>Crawl Histories</h3>
<ul id='crawl_histories'>
  <% @crawler_config.crawl_histories.each do |crawl_history| %>
    <li>
      <%= crawl_history.crawlHistoryId %> <%= crawl_history.startTime %> <%= crawl_history.endTime %> <%= crawl_history.ip %> <%= link_to crawl_history.totalTimeInSecs, [@crawler_config, crawl_history] %>
    </li>
  <% end %>
</ul>