config/routes.rb
require 'api_constraints'

ClickerAutomationApi::Application.routes.draw do

  devise_for :dusers

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :crawler_configs do
        resources :crawl_histories do
          get :manage, :on => :collection
        end
      end
      
      resources :crawler_configs
      resources :crawl_histories
    end
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :dusers
  end
  
  resources :crawler_configs do
    resources :crawl_histories
  end

  root :to => 'crawler_configs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClickerAutomationApi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
	    <div class='flash' id='<%= key %>'>
	      <%= value %>
	    </div>
	<% end %>

<h2><%= link_to "Clicker Automation", root_path %></h2>
<br>

<nav>
    <% if duser_signed_in? %>
      Signed in as <%= current_duser.email %>
      <%= link_to "Sign out", destroy_duser_session_path, :method => :delete%>
    <% else %>
      <%= link_to "Sign up", new_duser_registration_path %>
      <%= link_to "Sign in", new_duser_session_path %>
    <% end %>
   	<%= admins_only do %>
	<%= link_to "Admin", admin_root_path %><br>
	<% end %>
</nav>
<%= yield %>

</body>
</html>